// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: protos/translation2.proto

package translation2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Translation2Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *Translation2Input) Reset() {
	*x = Translation2Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_translation2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Translation2Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation2Input) ProtoMessage() {}

func (x *Translation2Input) ProtoReflect() protoreflect.Message {
	mi := &file_protos_translation2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation2Input.ProtoReflect.Descriptor instead.
func (*Translation2Input) Descriptor() ([]byte, []int) {
	return file_protos_translation2_proto_rawDescGZIP(), []int{0}
}

func (x *Translation2Input) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Translation2Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *Translation2Output) Reset() {
	*x = Translation2Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_translation2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Translation2Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation2Output) ProtoMessage() {}

func (x *Translation2Output) ProtoReflect() protoreflect.Message {
	mi := &file_protos_translation2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation2Output.ProtoReflect.Descriptor instead.
func (*Translation2Output) Descriptor() ([]byte, []int) {
	return file_protos_translation2_proto_rawDescGZIP(), []int{1}
}

func (x *Translation2Output) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_protos_translation2_proto protoreflect.FileDescriptor

var file_protos_translation2_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x32, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x22, 0x28, 0x0a, 0x12,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x32, 0x53, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x12, 0x43, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x65, 0x32, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x10, 0x5a, 0x0e, 0x2e,
	0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_translation2_proto_rawDescOnce sync.Once
	file_protos_translation2_proto_rawDescData = file_protos_translation2_proto_rawDesc
)

func file_protos_translation2_proto_rawDescGZIP() []byte {
	file_protos_translation2_proto_rawDescOnce.Do(func() {
		file_protos_translation2_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_translation2_proto_rawDescData)
	})
	return file_protos_translation2_proto_rawDescData
}

var file_protos_translation2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_translation2_proto_goTypes = []interface{}{
	(*Translation2Input)(nil),  // 0: protos.Translation2Input
	(*Translation2Output)(nil), // 1: protos.Translation2Output
}
var file_protos_translation2_proto_depIdxs = []int32{
	0, // 0: protos.Translation2.Translate2:input_type -> protos.Translation2Input
	1, // 1: protos.Translation2.Translate2:output_type -> protos.Translation2Output
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_translation2_proto_init() }
func file_protos_translation2_proto_init() {
	if File_protos_translation2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_translation2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Translation2Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_translation2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Translation2Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_translation2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_translation2_proto_goTypes,
		DependencyIndexes: file_protos_translation2_proto_depIdxs,
		MessageInfos:      file_protos_translation2_proto_msgTypes,
	}.Build()
	File_protos_translation2_proto = out.File
	file_protos_translation2_proto_rawDesc = nil
	file_protos_translation2_proto_goTypes = nil
	file_protos_translation2_proto_depIdxs = nil
}
